### PR TITLE
Convert to Python 3

### LINKED ISSUE #36: Support Python 3
With Python 2 finally [being EOL](https://www.python.org/downloads/release/python-2718/), it's time to ensure full Python 3 compatibility or even require Python 3. You may also consider joining the Python 3 alliance: https://python3statement.org/

Making TKperf compatible with Python 3 will require some conversion work. I ran all files through the `2to3` tool, and the result looked reasonable on a quick glance. I was able to run TKperf with one additional change, but haven't tested a full benchmark yet.

The dependency lists in the README should also be updated. Many of the dependencies are no longer available for Python 2 in recent Debian/Ubuntu versions, but they can be adapted for Python 3 easily.

### PR DESCRIPTION
**Pull request by onitake**
Conversion mostly done with the help of `2to3`.
Not fully tested yet.

Fixes: #36

### CODE REVIEW

**Comment by gschoenberger** [comment]
I think universal_newlines would be a great choice, as we might support Python versions < 3.7!

**Comment by onitake** [comment]
All right, I added the `universal_newlines` flag and removed the str.decode calls.

**Comment by Velociraptor85** [comment]
So my testruns worked - as far as I can tell https://github.com/onitake/TKperf/pull/1

**Comment by onitake** [comment]
Ok, I merged your changes. Looks like there were a few more Popen calls. :sweat_smile:

**Comment by gschoenberger** [comment]
I made a full TKperf run with a SSD performance test on an USB stick and had no problems with the current Python3 code.
I guess I will make a new release after I have finished my tests.

Thanks for the great support!

**Comment by tniedermeier** [comment]
Thanks for the great support @onitake also from my side! I also started a TKperf test (new Python3 code) with an Intel SSD, seems fine so far. But due to the large size of the SSD, the test isn't finished yet.

**Comment by tniedermeier** [comment]
I also made a full TKperf run with the current Python3 code. Test was fine, all plots and xml file processed, but mention the prompt regarding matplotlib at the end:

`$ sudo /usr/local/bin/tkperf ssd IntelD3S4520 /dev/sdb -nj 4 -iod 32 -rfb
[sudo] password for pmtest:
!!!Attention!!!
All data on /dev/sdb will be lost!
Are you sure you want to continue? (In case you really know what you are doing.)
Press 'y' to continue, any key to stop:
y
Starting ssd mode...
Testing device:
        Model Number:       INTEL SSDSC2KB019TZ
        Serial Number:      BTYI125202VJ1P9DGN
        Firmware Revision:  7CV10100
        Media Serial Num:
        Media Manufacturer:
        device size with M = 1000*1000:     1920383 MBytes (1920 GB)
        write-caching =  1 (on)
Device Logical Sector Size: 512
Device Physical Sector Size: 4096
Starting test: lat
Starting test: iops
Starting test: writesat
Starting test: tp

Bad key "lines.markeredgecolor" on line 12 in
/usr/share/matplotlib/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "lines.markerfacecolor" on line 11 in
/usr/share/matplotlib/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
`

**Pull request merged**
